 
flutter_application_path='../flutter_module'
load File.join(flutter_application_path, '.iOS', 'Flutter', 'podhelper.rb')


 #platform :ios, '15.6'

target 'FlutterNativeDemo' do
  install_all_flutter_pods(flutter_application_path)
  use_frameworks!
post_install do |installer|
  flutter_post_install(installer)
end

end
